### ISSUE TITLE
Only Some Version of riscv-gnu-toolchain can build this project

### ISSUE THREAD

**Issue by zengfan1992** [renyangang/riscv-mcu#1]
I try a lot of version for iscv-gnu-toolchain, only Some Version can build this project
https://github.com/riscv-collab/riscv-gnu-toolchain/tree/2023.01.03

Code in boot.s can not be compile, I don't know what it does, but it doesn't seem like removing this line has any effect.
.insn 4, 0x8000007F

**Comment by renyangang** [comment]
what is the error prompt when unable to compile?

**Comment by zengfan1992** [comment]
riscv32-unknown-linux-gnu-as -march=rv32i -mabi=ilp32  -I examples  -I bsp/common  -I bsp/gpio  -I bsp/interrupt  -I bsp/uart  -I bsp/iic  -I bsp/timer -o objs/boot.o boot.s
boot.s: Assembler messages:
boot.s:5: Error: value conflicts with instruction length `4,0x8000007F'
make: *** [Makefile:52: objs/boot.o] Error 1

**Comment by renyangang** [comment]
the gcc version I use: 
riscv32-unknown-linux-gnu-as -version
GNU assembler (GNU Binutils) 2.40.0.20230314
Copyright (C) 2023 Free Software Foundation, Inc.
This program is free software; you may redistribute it under the terms of
the GNU General Public License version 3 or later.

from the prompt, it should be that this version of as cannot recognize the syntax of `. insn 4, 0x8000007F`. I will change this to: `. insn 0x8000007F`.  You can try this

**Comment by zengfan1992** [comment]
2023.01.03 GNU assembler (GNU Binutils) 2.43.1
.insn 0x8000007F works
